## @file
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

#
# Include sub-makefiles
#
include $(PATH_SUB_CURRENT)/plugins/Makefile.kmk
include $(PATH_SUB_CURRENT)/gui/Makefile.kmk

include $(FILE_KBUILD_SUB_FOOTER)

