@echo off
if exist ft2lib.lib del ft2lib.lib
wlib -b -q ft2lib.lib + autofit\autofit.obj
wlib -b -q ft2lib.lib + base\ftbase.obj
wlib -b -q ft2lib.lib + base\ftinit.obj
wlib -b -q ft2lib.lib + base\ftglyph.obj
wlib -b -q ft2lib.lib + base\ftsystem.obj
wlib -b -q ft2lib.lib + base\ftbitmap.obj
wlib -b -q ft2lib.lib + base\ftbdf.obj
wlib -b -q ft2lib.lib + base\fttype1.obj
wlib -b -q ft2lib.lib + bdf\bdf.obj
wlib -b -q ft2lib.lib + cache\ftcache.obj
wlib -b -q ft2lib.lib + cff\cff.obj
wlib -b -q ft2lib.lib + cid\type1cid.obj
wlib -b -q ft2lib.lib + gzip\ftgzip.obj
wlib -b -q ft2lib.lib + lzw\ftlzw.obj
wlib -b -q ft2lib.lib + otvalid\otvalid.obj
wlib -b -q ft2lib.lib + pcf\pcf.obj
wlib -b -q ft2lib.lib + pfr\pfr.obj
wlib -b -q ft2lib.lib + psaux\psaux.obj
wlib -b -q ft2lib.lib + pshinter\pshinter.obj
wlib -b -q ft2lib.lib + psnames\psnames.obj
wlib -b -q ft2lib.lib + raster\raster.obj
wlib -b -q ft2lib.lib + sfnt\sfnt.obj
wlib -b -q ft2lib.lib + smooth\smooth.obj
wlib -b -q ft2lib.lib + truetype\truetype.obj
wlib -b -q ft2lib.lib + type1\type1.obj
wlib -b -q ft2lib.lib + type42\type42.obj
wlib -b -q ft2lib.lib + winfonts\winfnt.obj
