#ifndef ludjvu_idl
#define ludjvu_idl

/*
 *
 *  LuDjvuDocument
 *
 */

#include <ludoc.idl>


interface LuDjvuDocument : LuDocument
{

#ifdef __SOMIDL__

    implementation 
    {
	    void *data;

        loadFile: override;
        getBpp: override;
        isScalable: override;
        getPageCount: override;
        getPageSize: override;
        renderPageToPixbuf: override;
        getThumbnailSize: override;
        getThumbnail: override;
        isSaveable: override;
        saveAs: override;

        somDefaultInit: override, init;
        somDestruct: override;
    };

#endif // __SOMIDL__

};

#endif // ludjvu_idl
